/* AUTO-GENERATED by generate-projects.mjs — curated from t.me/donishyarportfolio (2026-06-11). */
export const CAT_COLOR = {
  "POSTER": "#ff5a1f",
  "LOGO": "#c9ff3d",
  "SOCIAL": "#8a6bff",
  "MOTION": "#57b0ff",
  "3D": "#ff3d6e",
  "VIDEO": "#ffd23e",
  "BRAND": "#5ce8c4",
  "PACKAGE": "#ffa3d1"
};

export const CATEGORIES = ["ALL","POSTER","3D","SOCIAL","PACKAGE","MOTION","VIDEO","BRAND","LOGO"];

export const PROJECTS = [
  {
    "id": "shafa-key-visual-series",
    "title": "Shafa Key Visual Series",
    "client": "Shafa",
    "year": "2025",
    "cat": "POSTER",
    "tags": [
      "KEY VISUAL",
      "SPLASH",
      "BEVERAGE"
    ],
    "cover": "/work/post132_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post132_photo0.jpg",
        "w": 639,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post132_photo3.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post132_photo1.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post132_photo2.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post142_photo1.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post142_photo0.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post196_photo1.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post196_photo8.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post196_photo9.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post196_photo2.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post196_photo3.jpg",
        "w": 450,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post196_photo4.jpg",
        "w": 533,
        "h": 800
      }
    ],
    "blurb": [
      "Hero key visuals for the Shafa beverage range — cola, orange, limonade, pomegranate and the fruit-juice line — built as dramatic Photoshop composites.",
      "Spiraling liquid splashes, sunset beaches and orchard scenes give every flavor its own cinematic stage."
    ],
    "role": "Design · Art Direction",
    "tools": "Photoshop"
  },
  {
    "id": "hype-energy-cgi-series",
    "title": "Hype Energy CGI Series",
    "client": "Hype Energy",
    "year": "2025",
    "cat": "3D",
    "tags": [
      "CGI",
      "ENERGY DRINK",
      "3D"
    ],
    "cover": "/work/post225_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post225_photo0.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo4.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo3.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo7.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo5.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo2.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo8.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo6.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo1.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post225_photo9.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post235_photo3.jpg",
        "w": 622,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post235_photo1.jpg",
        "w": 622,
        "h": 800
      }
    ],
    "blurb": [
      "Fifteen CGI product shots of the Hype Energy MFP and candy-striped Buzz Marshmallow cans, staged from beach splashes and neon streaks to night streets and gaming rooms.",
      "Blender animations and a SORA-assisted Lamborghini spot extend the cans into motion."
    ],
    "role": "3D · Art Direction",
    "tools": "Blender · After Effects"
  },
  {
    "id": "safa-tyor-food-campaign",
    "title": "Safa Tyor Food Campaign",
    "client": "Safa Tyor",
    "year": "2025",
    "cat": "SOCIAL",
    "tags": [
      "FOOD",
      "CAROUSEL",
      "REELS"
    ],
    "cover": "/work/post38_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post38_photo0.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post38_photo5.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post38_photo3.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post38_photo1.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post38_photo2.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "video",
        "src": "/work/post63_video0.mp4",
        "poster": "/work/post63_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post63_video1.mp4",
        "poster": "/work/post63_frame1.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post63_video2.mp4",
        "poster": "/work/post63_frame2.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post63_video3.mp4",
        "poster": "/work/post63_frame3.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post63_video4.mp4",
        "poster": "/work/post63_frame4.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post63_video5.mp4",
        "poster": "/work/post63_frame5.jpg",
        "w": 1080,
        "h": 1350
      },
      {
        "type": "video",
        "src": "/work/post63_video6.mp4",
        "poster": "/work/post63_frame6.jpg",
        "w": 1080,
        "h": 1920
      }
    ],
    "blurb": [
      "A full food content system for Safa Tyor poultry: a red-branded step-by-step recipe carousel plus eight vertical reels mixing filmed and AI-generated footage.",
      "Glazed chicken, bolani and a Ramadan iftar table carry the rooster brand across Instagram with Dari copy throughout."
    ],
    "role": "Design · Content Direction",
    "tools": "Photoshop · Premiere"
  },
  {
    "id": "hi-dairy-packaging",
    "title": "Hi Dairy Packaging",
    "client": "Pamir Cola",
    "year": "2026",
    "cat": "PACKAGE",
    "tags": [
      "PACKAGING",
      "DAIRY",
      "CGI"
    ],
    "cover": "/work/post320_photo2.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post320_photo2.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post320_photo3.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post320_photo1.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post320_photo0.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post247_photo1.jpg",
        "w": 470,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post247_photo3.jpg",
        "w": 470,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post247_photo0.jpg",
        "w": 470,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post247_photo6.jpg",
        "w": 470,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post247_photo4.jpg",
        "w": 470,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post247_photo2.jpg",
        "w": 470,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post247_photo5.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post324_photo0.jpg",
        "w": 640,
        "h": 800
      }
    ],
    "blurb": [
      "Packaging for the 'hi' dairy line — milk, cream, cocoa, pistachio, banana, date and honey-cream tetra packs rendered in high-end CGI.",
      "A chocolate-and-milk splash wrap and a carton nested inside an open pistachio shell push FMCG packshots into campaign territory."
    ],
    "role": "Packaging Design · CGI",
    "tools": "Illustrator · Photoshop"
  },
  {
    "id": "eid-campaign-films",
    "title": "Eid Campaign Films",
    "client": "Various Clients",
    "year": "2026",
    "cat": "MOTION",
    "tags": [
      "EID",
      "3D",
      "ANIMATION"
    ],
    "cover": "/work/post17_cover0.jpg",
    "preview": "/work/post17_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post17_video0.mp4",
        "poster": "/work/post17_frame0.jpg",
        "w": 848,
        "h": 464
      },
      {
        "type": "video",
        "src": "/work/post77_video0.mp4",
        "poster": "/work/post77_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post77_video1.mp4",
        "poster": "/work/post77_frame1.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post76_video0.mp4",
        "poster": "/work/post76_frame0.jpg",
        "w": 1280,
        "h": 720
      },
      {
        "type": "video",
        "src": "/work/post314_video0.mp4",
        "poster": "/work/post314_frame0.jpg",
        "w": 1280,
        "h": 720
      },
      {
        "type": "video",
        "src": "/work/post314_video1.mp4",
        "poster": "/work/post314_frame1.jpg",
        "w": 1280,
        "h": 720
      }
    ],
    "blurb": [
      "Eid greeting films for Khooban Cola, Anar Dara holding and Heydari Dental Clinic, led by a 3D icosahedron wrapped in white Arabic calligraphy.",
      "Glowing gold lanterns, geometric ornaments and embossed logo reveals give each client a festive signature in motion."
    ],
    "role": "Motion Design · 3D",
    "tools": "After Effects · Blender"
  },
  {
    "id": "ler-canada-poster-series",
    "title": "LER Canada Poster Series",
    "client": "LER Canada",
    "year": "2025",
    "cat": "POSTER",
    "tags": [
      "AD",
      "EQUIPMENT",
      "CAMPAIGN"
    ],
    "cover": "/work/post18_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post18_photo0.jpg",
        "w": 800,
        "h": 640
      },
      {
        "type": "image",
        "src": "/work/post20_photo0.jpg",
        "w": 800,
        "h": 640
      },
      {
        "type": "image",
        "src": "/work/post21_photo0.jpg",
        "w": 800,
        "h": 640
      },
      {
        "type": "image",
        "src": "/work/post22_photo0.jpg",
        "w": 800,
        "h": 400
      },
      {
        "type": "image",
        "src": "/work/post23_photo0.jpg",
        "w": 800,
        "h": 351
      }
    ],
    "blurb": [
      "A five-piece ad set for London Equipment Rentals: scissor and boom lift posters plus wide web banners under the 'Elevate Efficiency' headline.",
      "A disciplined navy-and-orange system flips between light and dark variants while keeping feature icons and CTAs consistent."
    ],
    "role": "Design",
    "tools": "Photoshop · Illustrator"
  },
  {
    "id": "pamir-cola-ai-commercials",
    "title": "Pamir Cola AI Commercials",
    "client": "Pamir Cola",
    "year": "2026",
    "cat": "VIDEO",
    "tags": [
      "AI VIDEO",
      "BEVERAGE",
      "CAMPAIGN"
    ],
    "cover": "/work/post333_cover2.jpg",
    "preview": "/work/post333_video2.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post333_video0.mp4",
        "poster": "/work/post333_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post333_video1.mp4",
        "poster": "/work/post333_frame1.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post333_video2.mp4",
        "poster": "/work/post333_frame2.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post193_video0.mp4",
        "poster": "/work/post193_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post193_video1.mp4",
        "poster": "/work/post193_frame1.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post101_video0.mp4",
        "poster": "/work/post101_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post101_video1.mp4",
        "poster": "/work/post101_frame1.jpg",
        "w": 1280,
        "h": 720
      },
      {
        "type": "video",
        "src": "/work/post212_video0.mp4",
        "poster": "/work/post212_frame0.jpg",
        "w": 1130,
        "h": 1500
      },
      {
        "type": "video",
        "src": "/work/post327_video0.mp4",
        "poster": "/work/post327_frame0.jpg",
        "w": 1080,
        "h": 1920
      }
    ],
    "blurb": [
      "Cinematic AI-generated commercials for the Pamir Cola family: a Shafa Cola bottle at a lavish Afghan feast, vapor-wrapped bottles erupting on ice, and drone sweeps over endless orange orchards.",
      "SORA and VEO3 footage is graded and finished in After Effects into broadcast-ready product spots."
    ],
    "role": "Direction · Motion Design",
    "tools": "SORA · VEO3 · After Effects"
  },
  {
    "id": "azin-travel-brand-suite",
    "title": "Azin Travel Brand Suite",
    "client": "Azin Travel",
    "year": "2026",
    "cat": "BRAND",
    "tags": [
      "IDENTITY",
      "TRAVEL",
      "SOCIAL"
    ],
    "cover": "/work/post50_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post50_photo0.jpg",
        "w": 566,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post4_photo0.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post5_photo0.jpg",
        "w": 800,
        "h": 767
      },
      {
        "type": "video",
        "src": "/work/post11_video0.mp4",
        "poster": "/work/post11_frame0.jpg",
        "w": 1280,
        "h": 720
      },
      {
        "type": "image",
        "src": "/work/post271_photo0.jpg",
        "w": 614,
        "h": 800
      },
      {
        "type": "video",
        "src": "/work/post12_video0.mp4",
        "poster": "/work/post12_frame0.jpg",
        "w": 1280,
        "h": 720
      }
    ],
    "blurb": [
      "A complete identity for Azin Travel: the negative-space airplane logomark, business cards, social campaigns and animated promos in a signature teal.",
      "From Air Arabia fare posts in Herat to the Saudi branch announcement, one system covers print, social and motion."
    ],
    "role": "Brand Design · Motion",
    "tools": "Illustrator · Photoshop · After Effects"
  },
  {
    "id": "pamir-cola-product-posters",
    "title": "Pamir Cola Product Posters",
    "client": "Pamir Cola",
    "year": "2025",
    "cat": "POSTER",
    "tags": [
      "PRODUCT",
      "BEVERAGE",
      "PHOTOSHOP"
    ],
    "cover": "/work/post110_photo5.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post110_photo5.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo4.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo8.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo2.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo0.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo1.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo6.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo7.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post110_photo3.jpg",
        "w": 600,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post93_photo0.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post93_photo3.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post93_photo1.jpg",
        "w": 599,
        "h": 800
      }
    ],
    "blurb": [
      "Photoshop product posters across the whole Pamir Cola portfolio — Deniz peach, Shafa juices and limonade, Hi Milk and Havas Chips.",
      "Each SKU gets its own world: orchards, water splashes, a cow pasture and an astronaut on a yoghurt-and-basil moon."
    ],
    "role": "Design · Retouching",
    "tools": "Photoshop"
  },
  {
    "id": "logofolio",
    "title": "Logofolio",
    "client": "Various Clients",
    "year": "2026",
    "cat": "LOGO",
    "tags": [
      "LOGO",
      "IDENTITY",
      "CALLIGRAPHY"
    ],
    "cover": "/work/post342_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post342_photo0.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post10_photo0.jpg",
        "w": 800,
        "h": 432
      },
      {
        "type": "image",
        "src": "/work/post24_photo0.jpg",
        "w": 800,
        "h": 600
      },
      {
        "type": "image",
        "src": "/work/post241_photo0.jpg",
        "w": 800,
        "h": 722
      }
    ],
    "blurb": [
      "Selected marks from 2025–2026: the golden Pamir Cola mountain-and-wave logo, Golden Egg poultry concepts, the Persian calligraphic 'Ebtekar' logotype and the Radmehr tailoring badge.",
      "Calligraphy, badges and negative space put to work across beverage, poultry, homeware and craft clients."
    ],
    "role": "Logo Design",
    "tools": "Illustrator"
  },
  {
    "id": "shafa-limonade-campaign-films",
    "title": "Shafa Limonade Campaign Films",
    "client": "Shafa",
    "year": "2026",
    "cat": "VIDEO",
    "tags": [
      "AI VIDEO",
      "LEMONADE",
      "CAMPAIGN"
    ],
    "cover": "/work/post165_cover0.jpg",
    "preview": "/work/post165_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post165_video0.mp4",
        "poster": "/work/post165_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post206_video0.mp4",
        "poster": "/work/post206_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post207_video0.mp4",
        "poster": "/work/post207_frame0.jpg",
        "w": 1400,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post164_video0.mp4",
        "poster": "/work/post164_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post195_video0.mp4",
        "poster": "/work/post195_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post330_video0.mp4",
        "poster": "/work/post330_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post108_video0.mp4",
        "poster": "/work/post108_frame0.jpg",
        "w": 640,
        "h": 352
      }
    ],
    "blurb": [
      "A season-long film campaign for Shafa Limonade: a SORA beach ad, a splash-crown animation, an underwater bottle plunge, citrus-orchard b-roll and a football spot.",
      "AI-generated footage finished in After Effects carries the Dari tagline 'the start of an excitement' across every format."
    ],
    "role": "Direction · Motion Design",
    "tools": "SORA · VEO3 · After Effects"
  },
  {
    "id": "gulfood-dubai-2026",
    "title": "Gulfood Dubai 2026",
    "client": "Pamir Cola",
    "year": "2026",
    "cat": "BRAND",
    "tags": [
      "EXHIBITION",
      "EVENT",
      "CAMPAIGN"
    ],
    "cover": "/work/post285_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post285_photo0.jpg",
        "w": 800,
        "h": 597
      },
      {
        "type": "image",
        "src": "/work/post281_photo1.jpg",
        "w": 639,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post281_photo3.jpg",
        "w": 800,
        "h": 571
      },
      {
        "type": "image",
        "src": "/work/post281_photo0.jpg",
        "w": 666,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post281_photo2.jpg",
        "w": 600,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post267_photo0.jpg",
        "w": 450,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post267_photo1.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "video",
        "src": "/work/post286_video0.mp4",
        "poster": "/work/post286_frame0.jpg",
        "w": 1280,
        "h": 720
      },
      {
        "type": "video",
        "src": "/work/post266_video0.mp4",
        "poster": "/work/post266_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post290_video0.mp4",
        "poster": "/work/post290_frame0.jpg",
        "w": 1080,
        "h": 1350
      },
      {
        "type": "video",
        "src": "/work/post289_video0.mp4",
        "poster": "/work/post289_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post287_video0.mp4",
        "poster": "/work/post287_frame0.jpg",
        "w": 1280,
        "h": 720
      }
    ],
    "blurb": [
      "The full Pamir Cola presence at Gulfood Dubai 2026: a 3D-rendered exhibition booth with 'Strong Feel' and 'Nature Feel' lightbox key visuals, announcement graphics, teaser reels and a TV spot aired on GEM TV.",
      "From the Burj Khalifa logo wipe to branded coverage of the live booth, one campaign took an Afghan beverage group to Dubai."
    ],
    "role": "Art Direction · Design · Motion",
    "tools": "Photoshop · After Effects"
  },
  {
    "id": "berang-motor-posters",
    "title": "Berang Motor Posters",
    "client": "Berang Motor",
    "year": "2025",
    "cat": "POSTER",
    "tags": [
      "AUTOMOTIVE",
      "PRODUCT",
      "POSTER"
    ],
    "cover": "/work/post87_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post87_photo0.jpg",
        "w": 800,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post87_photo2.jpg",
        "w": 800,
        "h": 779
      },
      {
        "type": "image",
        "src": "/work/post87_photo1.jpg",
        "w": 800,
        "h": 533
      }
    ],
    "blurb": [
      "Three vehicle posters for Berang Co.: the gold-and-black BRG Crown 2025 rickshaw on a podium and two 200cc Emperor motorcycle ads.",
      "Red-neon and mountain-road backdrops give Afghan two- and three-wheelers full showroom drama."
    ],
    "role": "Design",
    "tools": "Photoshop"
  },
  {
    "id": "shafa-summer-social-campaign",
    "title": "Shafa Summer Social Campaign",
    "client": "Pamir Cola",
    "year": "2025",
    "cat": "SOCIAL",
    "tags": [
      "LIFESTYLE",
      "BEVERAGE",
      "CAMPAIGN"
    ],
    "cover": "/work/post172_photo1.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post172_photo1.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post172_photo3.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post172_photo5.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post172_photo2.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post172_photo4.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post172_photo6.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post172_photo0.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post155_photo0.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post155_photo8.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post155_photo4.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post155_photo5.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post155_photo2.jpg",
        "w": 533,
        "h": 800
      }
    ],
    "blurb": [
      "Social-first product visuals for the Shafa summer line: the five-flavor 330ml glass-bottle juice lineup, limonade poolside splashes, and a cola bottle beside an Afghan Kabuli pulao spread.",
      "Lifestyle flat-lays and golden-hour scenes translate key-visual polish into a daily Instagram feed."
    ],
    "role": "Design · Retouching",
    "tools": "Photoshop"
  },
  {
    "id": "cgi-soda-reel",
    "title": "CGI Soda Reel",
    "client": "Concept",
    "year": "2025",
    "cat": "3D",
    "tags": [
      "3D",
      "ANIMATION",
      "BEVERAGE"
    ],
    "cover": "/work/post35_cover0.jpg",
    "preview": "/work/post35_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post35_video0.mp4",
        "poster": "/work/post35_frame0.jpg",
        "w": 1280,
        "h": 720
      },
      {
        "type": "video",
        "src": "/work/post36_video0.mp4",
        "poster": "/work/post36_frame0.jpg",
        "w": 856,
        "h": 480
      }
    ],
    "blurb": [
      "Spec 3D animations of beverage cans: photoreal Red Bull cans in a shallow-focus studio setup and a red soda can ringed by flying strawberries and carbonation bubbles.",
      "Self-driven Blender studies in lighting, condensation and floating-fruit choreography."
    ],
    "role": "3D · Motion",
    "tools": "Blender · After Effects"
  },
  {
    "id": "pamir-cola-packaging-labels",
    "title": "Pamir Cola Packaging & Labels",
    "client": "Pamir Cola",
    "year": "2026",
    "cat": "PACKAGE",
    "tags": [
      "PACKAGING",
      "PRINT",
      "LABEL"
    ],
    "cover": "/work/post240_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post240_photo0.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post242_photo0.jpg",
        "w": 527,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post242_photo2.jpg",
        "w": 527,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post242_photo4.jpg",
        "w": 527,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post242_photo3.jpg",
        "w": 527,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post242_photo1.jpg",
        "w": 527,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post183_photo0.jpg",
        "w": 551,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post183_photo1.jpg",
        "w": 551,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post183_photo2.jpg",
        "w": 551,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post296_photo0.jpg",
        "w": 800,
        "h": 616
      },
      {
        "type": "image",
        "src": "/work/post296_photo1.jpg",
        "w": 800,
        "h": 616
      },
      {
        "type": "video",
        "src": "/work/post313_video0.mp4",
        "poster": "/work/post313_frame0.jpg",
        "w": 288,
        "h": 640
      }
    ],
    "blurb": [
      "Print-ready packaging across the group: a gold-patterned six-pack bottle carrier, Shafa and Alli juice pouch labels, Deniz 24-pack tray dielines and the gold-script Deniz water label seen in production.",
      "Five Shafa-liveried cooler fridge wraps carry the flavor system straight into retail."
    ],
    "role": "Packaging Design",
    "tools": "Illustrator · Photoshop"
  },
  {
    "id": "ehya-physiotherapy-content",
    "title": "Ehya Physiotherapy Content",
    "client": "Ehya Physiotherapy",
    "year": "2025",
    "cat": "SOCIAL",
    "tags": [
      "HEALTHCARE",
      "CAROUSEL",
      "REELS"
    ],
    "cover": "/work/post44_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post44_photo0.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post44_photo1.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post44_photo2.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post44_photo3.jpg",
        "w": 640,
        "h": 800
      },
      {
        "type": "video",
        "src": "/work/post72_video0.mp4",
        "poster": "/work/post72_frame0.jpg",
        "w": 1080,
        "h": 1920
      }
    ],
    "blurb": [
      "Patient education content for Ehya Physiotherapy Clinic in Herat: a green-and-white carousel on muscle and joint pain plus a filmed dry-needling reel.",
      "Clinical close-ups and Dari caption blocks make treatment explainers feel calm and credible."
    ],
    "role": "Design · Video Editing",
    "tools": "Photoshop · Premiere"
  },
  {
    "id": "shafa-juice-ai-films",
    "title": "Shafa Juice AI Films",
    "client": "Shafa",
    "year": "2026",
    "cat": "VIDEO",
    "tags": [
      "AI VIDEO",
      "JUICE",
      "PRODUCT"
    ],
    "cover": "/work/post187_cover2.jpg",
    "preview": "/work/post187_video2.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post187_video0.mp4",
        "poster": "/work/post187_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post187_video1.mp4",
        "poster": "/work/post187_frame1.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post187_video2.mp4",
        "poster": "/work/post187_frame2.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post187_video3.mp4",
        "poster": "/work/post187_frame3.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post187_video4.mp4",
        "poster": "/work/post187_frame4.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post295_video0.mp4",
        "poster": "/work/post295_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post303_video0.mp4",
        "poster": "/work/post303_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post182_video0.mp4",
        "poster": "/work/post182_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post218_video0.mp4",
        "poster": "/work/post218_frame0.jpg",
        "w": 1080,
        "h": 1920
      }
    ],
    "blurb": [
      "AI-assisted product films for the Shafa juice line — sour cherry, pomegranate, mango, orange and peach bottles staged in lush orchards and streams.",
      "Photorealistic pours, splash choreography and moody pomegranate teasers, all composited and finished in After Effects."
    ],
    "role": "Direction · Motion Design",
    "tools": "AI Video · After Effects"
  },
  {
    "id": "hi-dairy-billboards",
    "title": "Hi Dairy Billboards",
    "client": "Pamir Cola",
    "year": "2026",
    "cat": "POSTER",
    "tags": [
      "BILLBOARD",
      "OOH",
      "DAIRY"
    ],
    "cover": "/work/post319_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post319_photo0.jpg",
        "w": 800,
        "h": 342
      },
      {
        "type": "image",
        "src": "/work/post317_photo0.jpg",
        "w": 800,
        "h": 600
      },
      {
        "type": "image",
        "src": "/work/post318_photo0.jpg",
        "w": 600,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post337_photo0.jpg",
        "w": 800,
        "h": 374
      },
      {
        "type": "image",
        "src": "/work/post340_photo0.jpg",
        "w": 800,
        "h": 374
      }
    ],
    "blurb": [
      "Out-of-home campaign for the hi dairy range: blue billboards of milk, cream and cream-cheese cartons under the Dari tagline 'everything starts with hi'.",
      "Documented live above busy Kabul avenues, from Chowk-e Gulha to the city's main arteries."
    ],
    "role": "Design · Art Direction",
    "tools": "Photoshop"
  },
  {
    "id": "ai-motion-lab",
    "title": "AI Motion Lab",
    "client": "Self-Initiated",
    "year": "2026",
    "cat": "MOTION",
    "tags": [
      "AI",
      "EXPERIMENT",
      "MOTION"
    ],
    "cover": "/work/post339_cover0.jpg",
    "preview": "/work/post339_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post339_video0.mp4",
        "poster": "/work/post339_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post338_video0.mp4",
        "poster": "/work/post338_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post272_video0.mp4",
        "poster": "/work/post272_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post221_video0.mp4",
        "poster": "/work/post221_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "video",
        "src": "/work/post121_video0.mp4",
        "poster": "/work/post121_frame0.jpg",
        "w": 1080,
        "h": 1920
      }
    ],
    "blurb": [
      "Self-initiated AI motion studies: macro pomegranate seeds on deep red, a smoking faceted glass, a Pixar-style cow in a sunset meadow, a Kaaba parallax scene and a tropical beach film.",
      "SORA, Seedance and Midjourney generations composited and graded in After Effects."
    ],
    "role": "Direction · Motion",
    "tools": "SORA · Seedance · Midjourney · After Effects"
  },
  {
    "id": "ramadan-2026-campaign",
    "title": "Ramadan 2026 Campaign",
    "client": "Pamir Cola",
    "year": "2026",
    "cat": "BRAND",
    "tags": [
      "RAMADAN",
      "CAMPAIGN",
      "PACKAGING"
    ],
    "cover": "/work/post302_cover0.jpg",
    "preview": "/work/post302_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post302_video0.mp4",
        "poster": "/work/post302_frame0.jpg",
        "w": 1080,
        "h": 1550
      },
      {
        "type": "video",
        "src": "/work/post301_video0.mp4",
        "poster": "/work/post301_frame0.jpg",
        "w": 1080,
        "h": 1920
      },
      {
        "type": "image",
        "src": "/work/post304_photo0.jpg",
        "w": 800,
        "h": 600
      },
      {
        "type": "image",
        "src": "/work/post304_photo1.jpg",
        "w": 800,
        "h": 593
      },
      {
        "type": "image",
        "src": "/work/post306_photo1.jpg",
        "w": 600,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post306_photo0.jpg",
        "w": 600,
        "h": 800
      }
    ],
    "blurb": [
      "Pamir Cola's Ramadan 2026 push: an iftar-table key visual under lanterns and a mosque skyline, delivered as both poster and animation.",
      "A glowing night-street animation and a calligraphic gift box — designed, dielined and photographed in print — complete the campaign."
    ],
    "role": "Design · Motion",
    "tools": "Photoshop · After Effects · Illustrator"
  },
  {
    "id": "shafa-energy-drink-launch",
    "title": "Shafa Energy Drink Launch",
    "client": "Shafa",
    "year": "2025",
    "cat": "POSTER",
    "tags": [
      "ENERGY DRINK",
      "KEY VISUAL",
      "LAUNCH"
    ],
    "cover": "/work/post208_photo1.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post208_photo1.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post208_photo0.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post208_photo3.jpg",
        "w": 533,
        "h": 800
      },
      {
        "type": "image",
        "src": "/work/post208_photo2.jpg",
        "w": 533,
        "h": 800
      }
    ],
    "blurb": [
      "Launch visuals for Shafa Energy Drink: the black-and-gold can held in a sunlit gym, planted on a snowy mountain summit and flexed beside a bodybuilder.",
      "AI-assisted scene-building and Photoshop compositing position the can as instant peak-performance shorthand."
    ],
    "role": "Design",
    "tools": "Photoshop"
  },
  {
    "id": "hi-milk-kids-ad",
    "title": "Hi Milk Kids Ad",
    "client": "Pamir Cola",
    "year": "2026",
    "cat": "VIDEO",
    "tags": [
      "AI",
      "ANIMATION",
      "DAIRY"
    ],
    "cover": "/work/post270_cover0.jpg",
    "preview": "/work/post270_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post270_video0.mp4",
        "poster": "/work/post270_frame0.jpg",
        "w": 1080,
        "h": 1920
      }
    ],
    "blurb": [
      "A Pixar-style AI-animated commercial for hi cocoa milk: a boy in a striped hoodie reaching for the carton and straw in a pastel playroom.",
      "Character animation generated with AI and finished in After Effects for the Pamir Cola dairy brand."
    ],
    "role": "Direction · Motion",
    "tools": "AI Video · After Effects"
  },
  {
    "id": "ontario-door-supply-identity",
    "title": "Ontario Door Supply Identity",
    "client": "Ontario Door Supply",
    "year": "2025",
    "cat": "BRAND",
    "tags": [
      "IDENTITY",
      "PRINT",
      "STATIONERY"
    ],
    "cover": "/work/post7_photo0.jpg",
    "preview": null,
    "media": [
      {
        "type": "image",
        "src": "/work/post7_photo0.jpg",
        "w": 800,
        "h": 480
      },
      {
        "type": "image",
        "src": "/work/post8_photo0.jpg",
        "w": 800,
        "h": 480
      }
    ],
    "blurb": [
      "A compact identity for Ontario Door Supply in London, Ontario: a line-art open-door logo, banner system and the director's business card.",
      "Warm brown panels and angled door photography keep the trade brand sturdy and legible."
    ],
    "role": "Brand Design",
    "tools": "Illustrator · Photoshop"
  },
  {
    "id": "green-apple-dental-reels",
    "title": "Green Apple Dental Reels",
    "client": "Green Apple Dental",
    "year": "2025",
    "cat": "VIDEO",
    "tags": [
      "DENTAL",
      "REELS",
      "HEALTHCARE"
    ],
    "cover": "/work/post74_cover0.jpg",
    "preview": "/work/post74_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post74_video0.mp4",
        "poster": "/work/post74_frame0.jpg",
        "w": 608,
        "h": 1080
      },
      {
        "type": "video",
        "src": "/work/post74_video1.mp4",
        "poster": "/work/post74_frame1.jpg",
        "w": 608,
        "h": 1080
      }
    ],
    "blurb": [
      "Short-form promo reels for the Green Apple dental clinic, led by a playful teeth-as-piano-keys composite.",
      "Cut for Instagram with bilingual captions, turning clinical services into thumb-stopping content."
    ],
    "role": "Design · Edit",
    "tools": "After Effects · Premiere"
  },
  {
    "id": "idea-afghan-animation",
    "title": "Idea Afghan Animation",
    "client": "Idea Afghan",
    "year": "2025",
    "cat": "MOTION",
    "tags": [
      "2D ANIMATION",
      "EXPLAINER",
      "PROMO"
    ],
    "cover": "/work/post91_cover0.jpg",
    "preview": "/work/post91_video0.mp4",
    "media": [
      {
        "type": "video",
        "src": "/work/post91_video0.mp4",
        "poster": "/work/post91_frame0.jpg",
        "w": 576,
        "h": 720
      }
    ],
    "blurb": [
      "Flat-design 2D animated promo for Idea Afghan — mint skies, paper-cut clouds and a cast of animated characters.",
      "Scripted, illustrated and animated end-to-end in After Effects."
    ],
    "role": "Animation · Illustration",
    "tools": "After Effects · Illustrator"
  }
];
